### ISSUE TITLE
P-to-P Code Review aug-12-21

### ISSUE THREAD

**Issue by alef-garrido** [DanSam5K/Awesome-Books#6]
Great project!
I think the script is clean and there's good use of classes.

- My only suggestion is to use a 'main' tag inside your HTML so it will be more semantically correct. 

Great Job. :smile:

**Comment by Felipeg005** [comment]
Thank you for share your code Daniel.

It's looking and working nicely. :+1:

**Comment by DanSam5K** [comment]
- Thank you for all your feedback. 👍 👏  
- I will look into all the issues raised @alef-garrido and give honest considerations. 😄 👏  🥳
